// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbhvoopfpkhkodfmqbwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiaHZvb3BmcGtoa29kZm1xYndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzE0NDMsImV4cCI6MjA3MzEwNzQ0M30.yPS9TNtwhnaGyKTw1OjfkpQ3__MxokJhaS_ZXWOH4vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});